### ISSUE TITLE
Add tutorial / workshops section

### ISSUE THREAD

**Issue by cblgh** [dat-land/website#5]
Heya! 

We just talked about this site in the latest [comm-comm](https://github.com/dat-land/comm-comm/issues/6) meeting. 

One thing that [Diego](https://github.com/dpaez) mentioned was to collect tutorials and workshops as well as the existing modules and tutorials. This should be fairly easy given the underlying format (which I just now realized was [Enoki](https://github.com/enokidotsite/enoki)!)

Just writing this issue as a reminder for anyone with time to tackle it :3

**Comment by joehand** [comment]
If someone wants to jump on this, we'd love to move parts of the [cookbook](https://docs.datproject.org/http) section of the current docs over here. So that'll give us some content to seed this with.

**Comment by dpaez** [comment]
I would like to help! 
As a side note, we can think of using something like the node.js app showcase form (https://foundation.nodejs.org/application-showcase-form). Maybe could be in the form of an issue template.
